stages:
    - code-quality

pylint:
    only:
        refs:
            - main
    stage: code-quality
    image: python:3.10
    script:
        - pip install --upgrade pip
        - pip install -r requirements.txt
        - pip install pylint
        - pylint ./*.py

isort:
    only:
        refs:
            - main
    stage: code-quality
    image: python:3.10
    script:
        - pip install --upgrade pip
        - pip install -r requirements.txt
        - pip install isort
        - isort --check ./*.py

black:
    only:
        refs:
            - main
    stage: code-quality
    image: python:3.10
    script:
        - pip install --upgrade pip
        - pip install -r requirements.txt
        - pip install black
        - black --check ./*.py
